version: '3.8'  # Версия формата Compose

services:
  # Сервис базы данных PostgreSQL
  postgres:
    image: postgres:16                # Используем официальный образ PostgreSQL 16
    container_name: postgres-gamedb    # Имя контейнера (удобно для команд)
    restart: always                    # Автоматически перезапускать, если упал
    environment:
      POSTGRES_USER: postgres          # Имя пользователя
      POSTGRES_PASSWORD: 123 # Пароль
      POSTGRES_DB: gamedb               # Имя базы данных, которая создастся при старте
    ports:
      - "5432:5432"                     # Проброс порта: порт хоста 5432 -> порт контейнера 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # Монтируем том для сохранения данных
    healthcheck:                         # Проверка здоровья (для зависимостей)
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

# Определяем том для данных PostgreSQL
volumes:
  pgdata:
    # Том будет создан автоматически, данные сохранятся даже после удаления контейнера